# Generated by Django 3.2 on 2023-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeurlpost',
            name='url',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
