# Generated by Django 3.2 on 2023-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0002_qrcodeurlpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='qrCode'),
        ),
    ]
