# Generated by Django 3.2 on 2023-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0005_rename_shirt_size_qrcodeurlpost_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='page_url',
            field=models.CharField(choices=[('my-first-sub-page', 'My first sub page'), ('my-second-sub-page', 'My second sub page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Url'),
        ),
    ]
