# Generated by Django 3.2 on 2023-02-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0006_auto_20230213_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Url'),
        ),
    ]
