# Generated by Django 3.2 on 2023-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0007_alter_qrcodeurlpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='page_url',
            field=models.CharField(blank=True, choices=[('my-first-sub-page', 'My first sub page'), ('my-second-sub-page', 'My second sub page')], max_length=20),
        ),
    ]
