# Generated by Django 3.2 on 2023-02-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0008_alter_qrcodeurlpost_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodeurlpost',
            old_name='created_on',
            new_name='start_date',
        ),
    ]
