# Generated by Django 3.2 on 2023-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0009_rename_created_on_qrcodeurlpost_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeurlpost',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
