# Generated by Django 3.2 on 2023-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0012_alter_qrcodeurlpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='page_url',
            field=models.CharField(blank=True, choices=[('my-new-blog', 'My new blog'), ('my-second-blog', 'My second blog')], max_length=20),
        ),
    ]
