# Generated by Django 3.2 on 2023-02-14 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0013_alter_qrcodeurlpost_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeurlpost',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('c5552134-5a3b-4773-8eb7-2e27cf745f7d')),
        ),
    ]
