# Generated by Django 3.2 on 2023-02-14 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0014_qrcodeurlpost_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('a8c377ec-e7f0-47fe-be3d-d9cbbddf9673')),
        ),
    ]
