# Generated by Django 3.2 on 2023-02-14 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qrCodePlugin', '0017_alter_qrcodeurlpost_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeurlpost',
            name='uuid_field',
            field=models.UUIDField(default=uuid.UUID('0b426cff-7358-4203-b76c-e9884eabb7a0'), editable=False),
        ),
    ]
